### ISSUE TITLE
publish vbox image to s3 so other repos can build on top of it

### ISSUE THREAD

**Issue by lightsofapollo** [taskcluster/packer-boxes#7]

**Comment by petemoore** [comment]
@jonasfj What is the story with this repository - should we keep these issues open? Is it no longer needed as we deploy in Heroku, or should we keep it in case we want to deploy our services in e.g. AWS? If we close, let's close all 5 open issues, and push a new commit that empties the repository and leaves a README.md just to say this project is no longer used.

**Comment by jonasfj** [comment]
@gregarndt What the story... is this deprecated or still in use for AMIs?

**Comment by gregarndt** [comment]
No idea, looking at the commit history I don't see me ever using this.  Mostly it's James, and there is one issue opened by you: https://github.com/taskcluster/packer-boxes/issues/4

**Comment by gregarndt** [comment]
Also looks like this was last touched about 7 months before I joined.  Most likely good to close.

**Comment by petemoore** [comment]
@lightsofapollo if you happen to be around and spot this - let us know if you think we should keep it! :) Without deep diving, I wasn't too sure what the intention was - if the packer boxes were for services or workers. Maybe it is something that was superseded, or maybe it is a piece of magic which is only a few commits away from happening - so wouldn't want to bin it without first checking which. =)

**Comment by jonasfj** [comment]
Hmm, pretty sure we don't use it any more....
It was only if this was basis for the docker-worker ami or vagrant box...
We should just mark the repo deprecated..
Den 5. apr. 2016 6.38 AM skrev "Pete Moore" <notifications@github.com>:
